- src/main/java/com/example/usStore/dao/GroupBuyingDao.java
- src/main/java/com/example/usStore/domain/GroupBuying.java
> [ADD] 공동구매 domain, 공동구매 dao 대충 틀 구현

- src/main/java/com/example/usStore/dao/AccuseDao.java
- src/main/java/com/example/usStore/dao/KeyAlarmDao.java
- src/main/java/com/example/usStore/domain/Accuse.java
- src/main/java/com/example/usStore/domain/KeyAlarm.java
accuse & KeyAlarm Domain Class & DAO Class
> add : accuse & keyAlarm Domain Class & DAO Class

- src/main/webapp/WEB-INF/jsp/Product/Item.jsp
> [add] Item.jsp 구현

- src/main/webapp/WEB-INF/jsp/Product/addGroupBuying.jsp
[add] addGroupBuying.jsp 구현
- 공동구매 추가 입력 폼 구현
> [add] addGroupBuying.jsp 구현

- src/main/webapp/WEB-INF/jsp/Product/Item.jsp
[fix] item.jsp 수정
: "가격" -> "정가" 수정
> [fix] item.jsp 수정

- src/main/webapp/WEB-INF/jsp/Product/addGroupBuying.jsp
[fix] addGroupBuying.jsp 수정
: 할인율을 입력받음 -> 할인율을 입력 안 받음 (정가와 판매가를 비교하여 자동 할인율 계산하도록)
> [fix] addGroupBuying.jsp 수정

- src/main/webapp/WEB-INF/jsp/Product/doneGroupBuying.jsp
[add] doneGroupBuying.jsp (공동구매 입력폼 최종 확인) 구현
> [add] doneGroupBuying.jsp 구현

- src/main/webapp/WEB-INF/jsp/Product/groupBuying.jsp
[add] groupBuying.jsp (공동구매 게시글 목록) 구현
> [add] groupBuying.jsp (공동구매 게시글 목록) 구현

- src/main/webapp/WEB-INF/jsp/Product/groupBuying.jsp
[fix] groupBuying.jsp 수정
: item.productId 파라미터 전달함
> [fix] groupBuying.jsp 수정

- src/main/webapp/WEB-INF/jsp/Product/viewGroupBuying.jsp
> [add] viewGroupBuying.jsp 구현

- src/main/webapp/WEB-INF/jsp/Product/viewGroupBuying.jsp
[fix] viewGroupBuying.jsp 수정
: 삭제하기 , 수정하기 추가
> [fix] viewGroupBuying.jsp 수정

- src/main/java/com/example/usStore/controller/item/SecondHandFormController.java
- src/main/java/com/example/usStore/controller/mypage/AddAccuseController.java
- src/main/java/com/example/usStore/dao/AccuseDao.java
- src/main/java/com/example/usStore/domain/Accuse.java
- src/main/webapp/WEB-INF/jsp/product/secondHand.jsp
- src/main/webapp/WEB-INF/jsp/product/viewSecondHand.jsp
> [fix] 신고기능 & 중고거래기능 동기화

- src/main/java/com/example/usStore/controller/item/AuctionFormController.java
- src/main/webapp/WEB-INF/jsp/product/auction.jsp
- src/main/webapp/WEB-INF/jsp/product/viewAuction.jsp
[fix] auction participate price 입력 후 제출
> [fix] auction participate price 입력 후 제출

- src/main/webapp/WEB-INF/jsp/product/addGroupBuying.jsp
- src/main/webapp/WEB-INF/jsp/product/checkGroupBuying.jsp
- src/main/webapp/WEB-INF/jsp/product/groupBuying.jsp
- src/main/webapp/WEB-INF/jsp/product/item.jsp
- src/main/webapp/WEB-INF/jsp/product/viewGroupBuying.jsp
[fix] GroupBuying관련 모든 jsp, item.jsp 모든 인코딩 수정
> [fix] GroupBuying관련 모든 jsp, item.jsp 모든 인코딩 수정

- src/main/java/com/example/usStore/controller/mypage/AddAccuseController.java
- src/main/java/com/example/usStore/service/impl/MyPageImpl.java
- src/main/webapp/WEB-INF/jsp/account/accuseFunction.jsp
[add] 신고 기능 - 디비에 신고이유 작성 가능하게 구현
> [add] 신고 기능 - 디비에 신고이유 작성 가능하게 구현

- src/main/java/com/example/usStore/controller/item/GroupBuyingFormController.java
- src/main/java/com/example/usStore/controller/item/ItemFormController.java
- src/main/webapp/WEB-INF/jsp/product/addGroupBuying.jsp
- src/main/webapp/WEB-INF/jsp/product/checkGroupBuying.jsp
- src/main/webapp/WEB-INF/jsp/product/item.jsp
- src/main/webapp/WEB-INF/jsp/product/viewGroupBuying.jsp
[hotfix] 공동구매 한글 깨짐 수정, 각 jsp마다 go to Index가 실행되도록 수정
[fix] 공동구매 status null 에러 수정
> [hotfix] 공동구매 한글 깨짐 수정, 각 jsp마다 go to Index가 실행되도록 수정 [fix] 공동구매 status null 에러 수정

- src/main/java/com/example/usStore/controller/item/HandMadeFormController.java
- src/main/java/com/example/usStore/controller/item/ItemForm.java
- src/main/java/com/example/usStore/dao/mybatis/MybatisHandMadeDao.java
- src/main/java/com/example/usStore/domain/HandMade.java
> [fix] HandMade transaction 구현 중

- src/main/java/com/example/usStore/controller/item/HandMadeForm.java
- src/main/java/com/example/usStore/controller/item/HandMadeFormController.java
- src/main/java/com/example/usStore/dao/.gitignore
- src/main/java/com/example/usStore/dao/mybatis/MybatisHandMadeDao.java
- src/main/java/com/example/usStore/domain/HandMade.java
- src/main/resources/com/example/usStore/dao/mybatis/mapper/HandMadeMapper.xml
- src/main/webapp/WEB-INF/jsp/product/addHandMade.jsp
- src/main/webapp/WEB-INF/jsp/product/checkHandMade.jsp
- src/main/webapp/WEB-INF/remoting-servlet.xml
> [func] HandMade 구현 완료

- src/main/java/com/example/usStore/controller/item/GroupBuyingFormController.java
- src/main/webapp/WEB-INF/jsp/product/itemTop.jsp
> [add] delete alert 다시 구현

- src/main/java/com/example/usStore/controller/item/GroupBuyingFormController.java
- src/main/webapp/WEB-INF/jsp/product/itemTop.jsp
> [hotfix] 주석 설명, 세션관련 수정
